// src/main.tsx
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase, supabaseConfigured } from './lib/supabase';
import type { Chat, Message, Profile } from './types';
import './styles.css';

const MAX_MESSAGE = 2000;
const initials = (name='Stranger') => name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase() || '?';
const time = (v:string) => new Intl.DateTimeFormat([], {hour:'2-digit', minute:'2-digit'}).format(new Date(v));

function App(){
 const [session,setSession]=useState<any>(null); const [profile,setProfile]=useState<Profile|null>(null); const [chat,setChat]=useState<Chat|null>(null); const [peer,setPeer]=useState<Profile|null>(null); const [messages,setMessages]=useState<Message[]>([]);
 const [screen,setScreen]=useState<'auth'|'home'|'chat'>('auth'); const [authMode,setAuthMode]=useState<'login'|'signup'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [username,setUsername]=useState(''); const [busy,setBusy]=useState(false); const [searching,setSearching]=useState(false); const [text,setText]=useState(''); const [notice,setNotice]=useState(''); const [showSafety,setShowSafety]=useState(false); const [reason,setReason]=useState('Harassment or bullying');
 const channelRef=useRef<any>(null); const queueRef=useRef<any>(null); const bottomRef=useRef<HTMLDivElement>(null); const messageBoxRef=useRef<HTMLDivElement>(null);
 const toast=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(''),3200)};
 const loadProfile=async(u:any)=>{const {data,error}=await supabase.from('profiles').select('id,username,created_at').eq('id',u.id).maybeSingle();if(error)throw error;const p=data as Profile|null;setProfile(p);return p};
 const restore=async(u:any)=>{try{const p=await loadProfile(u);const {data}=await supabase.from('chats').select('*').eq('status','active').or(`user_a.eq.${u.id},user_b.eq.${u.id}`).maybeSingle();if(data){await enterChat(data as Chat)}}catch(e:any){toast(e.message||'Could not restore your session.')}};
 useEffect(()=>{if(!supabaseConfigured)return; supabase.auth.getSession().then(({data})=>{if(data.session){setSession(data.session);restore(data.session.user)} }); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)restore(s.user);else{setProfile(null);setChat(null);setPeer(null);setScreen('auth')}});return()=>subscription.unsubscribe()},[]);
 const enterChat=async(c:Chat)=>{if(!session?.user)return;setSearching(false);if(queueRef.current){await queueRef.current.unsubscribe();queueRef.current=null}if(channelRef.current)await channelRef.current.unsubscribe();setChat(c);const pid=c.user_a===session.user.id?c.user_b:c.user_a;const {data:p,error}=await supabase.from('profiles').select('id,username,created_at').eq('id',pid).single();if(error)throw error;setPeer(p as Profile);const {data:ms}=await supabase.from('messages').select('*').eq('chat_id',c.id).order('created_at',{ascending:true}).limit(200);setMessages((ms||[]) as Message[]);setScreen('chat');const ch=supabase.channel(`chat:${c.id}`);channelRef.current=ch;ch.on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`chat_id=eq.${c.id}`},({new:m}:any)=>setMessages(prev=>prev.some(x=>x.id===m.id)?prev:[...prev,m as Message]));ch.on('broadcast',{event:'ended'},()=>{setChat(null);setPeer(null);setMessages([]);setScreen('home');toast('Your stranger ended the chat.');});await ch.subscribe();};
 useEffect(()=>{const box=messageBoxRef.current;if(!box)return;const near=box.scrollHeight-box.scrollTop-box.clientHeight<120;if(near)bottomRef.current?.scrollIntoView({behavior:'smooth'})},[messages]);
 const find=async()=>{if(!session)return;if(searching){await leaveQueue();toast('Search cancelled.');return}setBusy(true);try{const {data,error}=await supabase.rpc('find_match');if(error)throw error;if(data){await enterChat(data as Chat)}else{setSearching(true);const ch=supabase.channel(`queue:${session.user.id}`);queueRef.current=ch;ch.on('postgres_changes',{event:'INSERT',schema:'public',table:'chats'},async({new:c}:any)=>{if(c.user_a===session.user.id||c.user_b===session.user.id)await enterChat(c as Chat)});await ch.subscribe();toast('Looking for someone…')}}catch(e:any){toast(e.message||'Could not start matchmaking.');setSearching(false)}finally{setBusy(false)}};
 const leaveQueue=async()=>{setSearching(false);if(queueRef.current){await queueRef.current.unsubscribe();queueRef.current=null}if(session)await supabase.rpc('leave_match_queue')};
 const endChat=async(rejoin=false)=>{if(!chat)return;const c=chat;if(channelRef.current){try{await channelRef.current.send({type:'broadcast',event:'ended',payload:{}})}catch{}await channelRef.current.unsubscribe();channelRef.current=null}await supabase.rpc('end_chat',{p_chat_id:c.id});setChat(null);setPeer(null);setMessages([]);setScreen('home');if(rejoin)window.setTimeout(find,100)};
 const send=async(e:React.FormEvent)=>{e.preventDefault();if(!chat||!session)return;const body=text.trim();if(!body)return;if(body.length>MAX_MESSAGE){toast(`Messages are limited to ${MAX_MESSAGE} characters.`);return}setText('');const {error}=await supabase.from('messages').insert({chat_id:chat.id,sender_id:session.user.id,body});if(error){setText(body);toast('Message could not be sent.')}};
 const auth=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{if(authMode==='signup'){if(username.trim().length<2)throw new Error('Choose a username with at least 2 characters.');const {error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{username:username.trim()}}});if(error)throw error;toast('Account created. Check your email if verification is enabled.')}else{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error}}catch(e:any){toast(e.message||'Authentication failed.')}finally{setBusy(false)}};
 const google=async()=>{const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)toast(error.message)};
 const logout=async()=>{await leaveQueue();if(channelRef.current)await channelRef.current.unsubscribe();await supabase.auth.signOut()};
 const saveProfile=async()=>{if(!profile)return;const name=profile.username.trim();if(name.length<2||name.length>24)return toast('Display name must be 2–24 characters.');const {error}=await supabase.from('profiles').update({username:name}).eq('id',profile.id);if(error)toast(error.code==='23505'?'That username is already taken.':error.message);else toast('Profile updated.')};
 const report=async()=>{if(!peer||!session)return;const {error}=await supabase.from('reports').insert({reporter_id:session.user.id,reported_user_id:peer.id,chat_id:chat?.id??null,reason});if(error)toast('Could not submit report.');else{setShowSafety(false);toast('Report submitted. Thank you.')}};
 const block=async()=>{if(!peer||!session)return;const {error}=await supabase.from('blocks').insert({user_id:session.user.id,blocked_user_id:peer.id});if(error&&error.code!=='23505')return toast('Could not block this user.');setShowSafety(false);toast('User blocked.');await endChat(false)};
 const title=useMemo(()=>screen==='chat'?'RandomChat — Conversation':'RandomChat — Meet someone new',[screen]);useEffect(()=>{document.title=title},[title]);
 if(!supabaseConfigured)return <main className="center"><div className="panel"><h1>RandomChat</h1><p>Supabase is not configured.</p><code>VITE_SUPABASE_URL<br/>VITE_SUPABASE_PUBLISHABLE_KEY</code></div></main>;
 return <main className="app">{notice&&<div className="toast" role="status">{notice}</div>}
 {screen==='auth'&&<section className="auth page"><div className="brand"><span className="mark">RC</span> Random<span>Chat</span></div><div className="auth-card panel"><div className="eyebrow">MEET SOMEONE NEW</div><h1>One stranger.<br/><span>One conversation.</span></h1><p className="muted">Start talking with someone you've never met, instantly.</p><div className="tabs"><button className={authMode==='login'?'active':''} onClick={()=>setAuthMode('login')}>Log in</button><button className={authMode==='signup'?'active':''} onClick={()=>setAuthMode('signup')}>Create account</button></div><form onSubmit={auth}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required autoComplete="email"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={6} required autoComplete={authMode==='signup'?'new-password':'current-password'}/></label>{authMode==='signup'&&<label>Username<input value={username} onChange={e=>setUsername(e.target.value)} maxLength={24} required/></label>}<button className="primary wide" disabled={busy}>{busy?'Working…':authMode==='signup'?'Create account':'Continue'}</button></form><button className="secondary wide" onClick={google}>Continue with Google</button><small>Be respectful. Never share sensitive information with strangers.</small></div></section>}
 {screen==='home'&&<section className="page"><header><div className="brand"><span className="mark">RC</span> Random<span>Chat</span></div><div className="actions"><button className="secondary" onClick={()=>profile&&setProfile({...profile})}>Profile</button><button className="secondary" onClick={logout}>Log out</button></div></header><div className="home-grid"><section className="hero panel"><div className="eyebrow">RANDOM MATCHMAKING</div><h2>Who will you<br/><span>meet today?</span></h2><p className="muted">No feeds. No follower counts. Just one real conversation at a time.</p><button className="primary hero-button" disabled={busy} onClick={find}>{searching?'Cancel search':'Find someone'} <b>↗</b></button><div className="safety"><span>✓ Report & block</span><span>✓ Private conversations</span></div></section><aside className="panel how"><h3>How it works</h3><div><b>01</b><p><strong>Find someone</strong><br/>Join the live matchmaking queue.</p></div><div><b>02</b><p><strong>Get paired</strong><br/>A private room is created for two.</p></div><div><b>03</b><p><strong>Talk freely</strong><br/>Skip anytime. You're always in control.</p></div></aside></div></section>}
 {screen==='chat'&&chat&&peer&&<section className="chat"><header><div className="person"><div className="avatar">{initials(peer.username)}</div><div><strong>{peer.username}</strong><small><i/> connected</small></div></div><div className="actions"><button className="secondary" onClick={()=>setShowSafety(true)}>Safety</button><button className="secondary" onClick={()=>endChat(true)}>Next</button></div></header><div className="messages" ref={messageBoxRef}>{messages.length===0&&<div className="empty"><div className="avatar big">{initials(peer.username)}</div><h3>Say hello to {peer.username}.</h3><p className="muted">This is a private conversation between the two of you.</p></div>}{messages.map(m=><div className={'message '+(m.sender_id===session.user.id?'mine':'')} key={m.id}><div className="bubble">{m.body}</div><time>{time(m.created_at)}</time></div>)}<div ref={bottomRef}/></div><form className="composer" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} maxLength={MAX_MESSAGE} placeholder="Say hello…" autoComplete="off"/><button className="primary" disabled={!text.trim()}>Send</button></form>{showSafety&&<div className="overlay"><div className="panel modal"><button className="close" onClick={()=>setShowSafety(false)}>×</button><h3>Safety</h3><p className="muted">Help keep RandomChat welcoming.</p><label>Reason<select value={reason} onChange={e=>setReason(e.target.value)}><option>Harassment or bullying</option><option>Spam or scam</option><option>Inappropriate content</option><option>Threatening behaviour</option><option>Other</option></select></label><div className="modal-actions"><button className="secondary" onClick={report}>Report</button><button className="danger" onClick={block}>Block & leave</button></div></div></div>}</section>}
 </main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
